import SwiftUI
import SafariServices

extension Color{static let paper=Color(uiColor:UIColor{ $0.userInterfaceStyle == .dark ? UIColor(red:0.07,green:0.09,blue:0.08,alpha:1):UIColor(red:0.96,green:0.95,blue:0.91,alpha:1)});static let ink=Color.primary;static let muted=Color.secondary;static let signal=Color(red:0.18,green:0.42,blue:0.33);static let raised=Color(uiColor:.secondarySystemBackground)}
struct Safari: UIViewControllerRepresentable{let url:URL;func makeUIViewController(context:Context)->SFSafariViewController{SFSafariViewController(url:url)};func updateUIViewController(_ uiViewController:SFSafariViewController,context:Context){}}
struct LinkItem:Identifiable{let id=UUID();let url:URL}

struct ArticleCard:View{let article:Article;@EnvironmentObject var bookmarks:Bookmarks;@Binding var link:LinkItem?
 var body:some View{VStack(alignment:.leading,spacing:12){HStack{Text(article.topicLabel.uppercased()).font(.caption.bold()).foregroundStyle(Color.signal);Spacer();Text(article.date.map{RelativeDateTimeFormatter().localizedString(for:$0,relativeTo:.now)} ?? "Recently").font(.caption).foregroundStyle(.secondary)}
 Button{if let u=article.articleURL{link = .init(url:u)}}label:{VStack(alignment:.leading,spacing:10){Text(article.title).font(.system(.title3,design:.serif,weight:.semibold)).multilineTextAlignment(.leading);Text(article.summary ?? "Open the original report for full context.").font(.system(.body,design:.serif)).foregroundStyle(.secondary).multilineTextAlignment(.leading)}}.buttonStyle(.plain)
 Divider();HStack{Text(article.source).font(.subheadline.bold());Spacer();Button{bookmarks.toggle(article)}label:{Image(systemName:bookmarks.has(article) ? "bookmark.fill":"bookmark").frame(width:44,height:44).foregroundStyle(Color.signal)}}}
 .padding(18).background(Color.raised,in:RoundedRectangle(cornerRadius:20)).overlay(RoundedRectangle(cornerRadius:20).stroke(.quaternary))}
}

struct WeatherCard:View{@ObservedObject var vm:WeatherVM
 var body:some View{VStack(alignment:.leading,spacing:14){HStack{Label("LOCAL SIGNAL",systemImage:"location.fill").font(.caption.bold()).foregroundStyle(Color.signal);Spacer();Button("Use current"){vm.useCurrent()}}
 HStack{Image(systemName:"magnifyingglass");TextField("Search address, place or landmark",text:$vm.query).submitLabel(.search).onSubmit{Task{await vm.search()}};Button("Search"){Task{await vm.search()}}}.padding(12).background(Color.paper,in:RoundedRectangle(cornerRadius:12))
 if !vm.places.isEmpty{VStack(spacing:0){ForEach(vm.places){p in Button{Task{await vm.choose(p)}}label:{VStack(alignment:.leading){Text(p.name).bold();if let d=p.displayName{Text(d).font(.caption).foregroundStyle(.secondary)}}.frame(maxWidth:.infinity,alignment:.leading).padding(10)}.buttonStyle(.plain);Divider()}}}
 if vm.loading && vm.weather == nil{ProgressView().frame(maxWidth:.infinity,minHeight:110)}else if let w=vm.weather{HStack{Image(systemName:symbol(w.weatherCode)).font(.system(size:38)).foregroundStyle(Color.signal);VStack(alignment:.leading){Text("\(w.temperature)°").font(.system(size:40,weight:.medium,design:.rounded));Text(w.condition).foregroundStyle(.secondary)};Spacer();VStack(alignment:.trailing){Text(w.resolvedPlace ?? w.place ?? "Location").bold();Text("Feels \(w.feelsLike)° · Rain \(w.rainChance)%").font(.caption);Text("NAQI \(w.aqiDisplay ?? w.aqi.map { String($0) } ?? "--")").font(.subheadline.bold()).foregroundStyle(Color.signal)}};Text(w.aqiStation.map{"CPCB station: \($0)"} ?? w.provider).font(.caption).foregroundStyle(.secondary)}
 if let e=vm.error{Text(e).font(.caption).foregroundStyle(.orange)}}.padding(18).background(Color.raised,in:RoundedRectangle(cornerRadius:20)).overlay(RoundedRectangle(cornerRadius:20).stroke(.quaternary))}
 func symbol(_ c:Int)->String{switch c{case 0:return "sun.max.fill";case 1...3:return "cloud.sun.fill";case 45,48:return "cloud.fog.fill";case 51...82:return "cloud.rain.fill";case 95...99:return "cloud.bolt.rain.fill";default:return "cloud.fill"}}
}

struct HomeView:View{@ObservedObject var news:NewsVM;@ObservedObject var weather:WeatherVM;@EnvironmentObject var prefs:Preferences;@State var link:LinkItem?;@State var picker=false
 var body:some View{NavigationStack{ScrollView{LazyVStack(alignment:.leading,spacing:16){Text(Date.now.formatted(.dateTime.weekday(.wide).month(.wide).day().year()).uppercased()).font(.caption.bold()).foregroundStyle(Color.signal);Text("Your intelligence,\ndistilled.").font(.system(size:42,weight:.medium,design:.serif));Text("A calm, high-signal briefing across the technologies, markets and ideas you care about.").font(.system(.body,design:.serif)).foregroundStyle(.secondary);WeatherCard(vm:weather)
 ScrollView(.horizontal,showsIndicators:false){HStack{chip("Today",nil);ForEach(Topics.all.filter{prefs.topics.contains($0.id)}){t in chip(t.label,t.id)}}}
 HStack{Text(news.selected.map(Topics.label) ?? "Today’s Briefing").font(.system(.title,design:.serif,weight:.semibold));Spacer();Text("\(news.articles.count)").foregroundStyle(Color.signal)}
 if let e=news.error{Text(e).padding().frame(maxWidth:.infinity,alignment:.leading).background(.orange.opacity(0.12),in:RoundedRectangle(cornerRadius:12))}
 if news.loading && news.articles.isEmpty{ProgressView().frame(maxWidth:.infinity,minHeight:220)}else if news.articles.isEmpty{ContentUnavailableView("No recent signal",systemImage:"newspaper",description:Text("Refresh or choose another topic."))}else{ForEach(news.articles){ArticleCard(article:$0,link:$link)}}}.padding(16)}.background(Color.paper.ignoresSafeArea()).navigationTitle("Signal").toolbar{ToolbarItemGroup(placement:.topBarTrailing){Button{Task{await news.load(refresh:true);await weather.load(refresh:true)}}label:{Image(systemName:"arrow.clockwise")};Button{picker=true}label:{Image(systemName:"slider.horizontal.3")}}}.refreshable{await news.load(refresh:true);await weather.load(refresh:true)}.task{await news.load();await weather.load()}.sheet(item:$link){Safari(url:$0.url).ignoresSafeArea()}.sheet(isPresented:$picker){TopicPicker()}}
 }
func chip(_ title:String,_ id:String?)->some View{Button{news.selected=id;Task{await news.load()}}label:{Text(title).font(.subheadline.bold()).padding(.horizontal,14).frame(height:38).background(news.selected==id ? Color.signal:Color.signal.opacity(0.12),in:Capsule()).foregroundStyle(news.selected==id ? .white:.primary)}}
}

struct TopicPicker:View{@EnvironmentObject var prefs:Preferences;@Environment(\.dismiss)var dismiss
 var body:some View{NavigationStack{List{Text("Choose the signals used in Today’s Briefing. Movies & Series remains in its own section.").foregroundStyle(.secondary);ForEach(Topics.groups,id:\.self){g in Section(g){ForEach(Topics.all.filter{$0.group==g}){t in Button{prefs.toggle(t.id)}label:{HStack{Text(t.label);Spacer();Image(systemName:prefs.topics.contains(t.id) ? "checkmark.circle.fill":"circle").foregroundStyle(Color.signal)}}.buttonStyle(.plain)}}}}.navigationTitle("Your Signals").toolbar{Button("Done"){dismiss()}}}}
}

struct TopicsView:View{@EnvironmentObject var prefs:Preferences;@State var link:LinkItem?;@State var feeds:[String:NewsVM]=[:]
 var body:some View{NavigationStack{List{ForEach(Topics.groups,id:\.self){g in Section(g){ForEach(Topics.all.filter{$0.group==g}){t in NavigationLink(t.label){TopicFeed(topic:t,prefs:prefs)}}}}}.navigationTitle("Topics")}}
}
struct TopicFeed:View{let topic:Topic;@StateObject var vm:NewsVM;@State var link:LinkItem?;init(topic:Topic,prefs:Preferences){self.topic=topic;let v=NewsVM(prefs);v.selected=topic.id;_vm=StateObject(wrappedValue:v)}
 var body:some View{ScrollView{LazyVStack(spacing:16){if vm.loading{ProgressView()}else{ForEach(vm.articles){ArticleCard(article:$0,link:$link)}}}.padding(16)}.background(Color.paper).navigationTitle(topic.label).refreshable{await vm.load(refresh:true)}.task{await vm.load()}.sheet(item:$link){Safari(url:$0.url)}}}

struct SavedView:View{@EnvironmentObject var bookmarks:Bookmarks;@State var link:LinkItem?;var body:some View{NavigationStack{ScrollView{LazyVStack(spacing:16){if bookmarks.items.isEmpty{ContentUnavailableView("Nothing saved",systemImage:"bookmark",description:Text("Save stories to read later."))}else{ForEach(bookmarks.items){ArticleCard(article:$0,link:$link)}}}.padding(16)}.background(Color.paper).navigationTitle("Saved").sheet(item:$link){Safari(url:$0.url)}}}}
struct SettingsView:View{@EnvironmentObject var prefs:Preferences;@EnvironmentObject var bookmarks:Bookmarks;@State var picker=false;var body:some View{NavigationStack{Form{Section("Appearance"){Picker("Theme",selection:$prefs.theme){ForEach(Theme.allCases){Text($0.rawValue.capitalized).tag($0)}}.pickerStyle(.segmented)};Section("Personalization"){Button("Selected signals: \(prefs.topics.count)"){picker=true};LabeledContent("Weather location",value:prefs.location.name)};Section("Data"){LabeledContent("Saved stories",value:String(bookmarks.items.count));Text("Optional Google and data.gov.in keys remain server-side. No API keys are embedded in the app.").font(.caption).foregroundStyle(.secondary)}}.navigationTitle("Settings").sheet(isPresented:$picker){TopicPicker()}}}}
